### PR TITLE
✨  scrape descriptions on encode

### PR DESCRIPTION
**Pull request by dmiller15**
Followup work to https://github.com/brentp/echtvar/pull/34.

I tried to tackle the task of INFO field description scraping requested in https://github.com/brentp/echtvar/issues/33. Found rust-htslib pretty ill-equipped for the task, but I'm way too much of a rust/c novice to delve deeply into the core of htslib. This could perhaps be done better using `bcf_hdr_get_hrec`.

In the end I made a short function to filter down the `HeaderRecord vector` using an `ID` value. Since there should only ever be one INFO header record with a particular ID, I return the description from the first of the remaining records. If it's not there I pass along the default value. On the way out I make sure to trim the `"` since the `update_header` function expects the descriptions to be unquoted.

In the `encoder_main` function I only call this function when the `field` `description` is not the default. I figure we'd want to give user priority in field naming.

As for how the check against the default is done, I couldn't really figure out how to get a default value for a field the way things were so I went ahead and made the `fields::default_description_string()` function public. I'm not sure if that's a good way of doing that so I'm open to suggestions.

Let me know if this is fine. Feel free to discard the PR if you want to go about this a different way.

### CODE REVIEW

**Comment by brentp** [comment]
@dmiller15 , this looks good to me. Ready from your end?

**Comment by dmiller15** [comment]
Just tested it, and it's still working as intended.

**Comment by brentp** [comment]
thank  you!

**Comment by brentp** [comment]
@dmiller15 , this fails tests/big.sh. Can you fix that?

**Comment by dmiller15** [comment]
Ok didn't notice that we'd added more tests, and the test logic is no longer true. I'll update that batch of tests and have a PR up today.

**Pull request merged**
